name: My First Workflow

on: push

jobs:
    first_job:
        name: First job
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Welcome message
              run: |
                echo "My first GH Actions job"
                ls -lrt
                cat README.md
            
            - name: Adding ASCII artwork using cowsay
              run: cowsay -f dragon "Run for cover, I am a Dragon....RAWW" >> dragon.txt  

            #- name: Name files
             # run: ls
            
            #- name: Read file
             # run: cat README.md