name: Exploring variable & secrets
on:
    push
env:                    # this is workflow level variables
    CONTAINER_REGISTRY: docker.io
    #DOCKER_USERNAME: abhishek123
    DOCKER_IMAGE: github-actions-image    
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker build
              run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest
              
            - name: Docker login
              #env:
                #DOCKER_PASSWORD: PaSS0WoRD          # this is step level
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
              
            - name: Docker publish
              run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest

    deploy:
        if: github.ref == 'refs/heads/main'                 # using if github.ref value is matched then run deploy
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest       

