name: Matrix conf
on:
    push
   
jobs:
    
    deploy:
        env:
            DOCKER_USERNAME: abhishekbakare
        strategy:                     # used to define strategy
            matrix:                   # matrix used here  
                os: [ubuntu-latest, ubuntu-22.04, windows-latest]
                image: [hello-world, nginx]

        runs-on: ${{ matrix.os }} 
     
        steps:
            - name: Docker login
              run: docker login --username=abhishekbakare --password=${{ secrets.DOCKER_PASSWORD }}

            - name: Get docker info
              run: docker info
            
            - name: Run images on ${{ matrix.image }} 
              run: docker run ${{ matrix.image }} 