name: Generate sequence jobs ASCII art

on: 
    push

jobs:
    first_ascii_job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Install cowsay 
              run: sudo apt-get install cowsay -y     

            - name: Execute cowsay cmd
              run: cowsay -f dragon "Run for cover, I am a Dragon....RAWW" >> dragon.txt 
            
            - name: Upload a file
              uses: actions/upload-artifact@v3
              with:
                name: upload-a-file
                path: dragon.txt

    test_ascii_job2:
        needs: first_ascii_job1
        runs-on: ubuntu-latest
        steps: 
            - name: Download a file
              uses: actions/download-artifact@v3
              with:
                name: upload-a-file
              
            - name: Check file exist
              run: grep -i "Dragon" dragon.txt
            
    deploy_job_3:
        needs: [first_ascii_job1, test_ascii_job2]
        runs-on: ubuntu-latest
        steps:

            - name: Download a file
              uses: actions/download-artifact@v3
              with:
                name: upload-a-file

            - name: Read file
              run: cat dragon.txt
              
            - name: Deploy
              run: echo "Deploying......"    

