name: Generate ASCII art

on: 
    push

jobs:
    first_ascii_job1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Install cowsay 
              run: sudo apt-get install cowsay -y     

            - name: Execute cowsay cmd
              run: cowsay -f dragon "Run for cover, I am a Dragon....RAWW" >> dragon.txt 
            
            - name: Sleep
              run: sleep 30  

    test_ascii_job2:
        needs: first_ascii_job1
        runs-on: ubuntu-latest
        steps: 
            - name: Sleep 10 sec
              run: sleep 10
            
            - name: Check file exist
              run: grep -i "Dragon" dragon.txt
            
    deploy_job_3:
        needs: [first_ascii_job1, test_ascii_job2]
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              run: cat dragon.txt
              
            - name: Deploy
              run: echo "Deploying......"    

